import 'package:dio/dio.dart';
import 'package:realview_code_exercise/core/constants/constants.dart';
import 'package:realview_code_exercise/features/author_search/data/models/author_details_model.dart';
import 'package:realview_code_exercise/features/author_search/data/models/author_search_response_model.dart';
import 'package:retrofit/retrofit.dart';

part 'author_api_client.g.dart';

/// Retrofit API client for the OpenLibrary authors endpoints.
/// Implementation is generated by [retrofit_generator].
@RestApi(baseUrl: AppEndpoints.baseUrl)
abstract class AuthorApiClient {
  factory AuthorApiClient(Dio dio) = _AuthorApiClient;

  /// GET /search/authors.json?q={query}
  @GET(AppEndpoints.authorSearch)
  Future<AuthorSearchResponseModel> searchAuthors(
    @Query('q') String query,
  );

  /// GET /authors/{key}.json
  @GET('/authors/{key}.json')
  Future<AuthorDetailsModel> getAuthorDetails(
    @Path('key') String key,
  );
}
